<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatalogoV4Seeder extends Seeder
{
    public function run(): void
    {
        $productos = [
            [
                'nombre' => 'Doritos Mega Queso 21g',
                'descripcion' => 'Delicioso snack Doritos Mega Queso 21g. Marca: Doritos.',
                'marca' => 'Doritos',
                'categoria' => 'Tortillas de Maiz, Queso',
                'precio' => 0.32,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/doritos_mega_queso_21g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Doritos Mega Queso 145g',
                'descripcion' => 'Delicioso snack Doritos Mega Queso 145g. Marca: Doritos.',
                'marca' => 'Doritos',
                'categoria' => 'Tortillas de Maiz, Queso',
                'precio' => 1.96,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/doritos_mega_queso_145g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Doritos Mega Queso 400g',
                'descripcion' => 'Delicioso snack Doritos Mega Queso 400g. Marca: Doritos.',
                'marca' => 'Doritos',
                'categoria' => 'Tortillas de Maiz, Queso',
                'precio' => 4.5,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/doritos_mega_queso_400g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Doritos Maíz Amarillo 21g',
                'descripcion' => 'Delicioso snack Doritos Maíz Amarillo 21g. Marca: Doritos.',
                'marca' => 'Doritos',
                'categoria' => 'Tortillas de Maiz, Naturales',
                'precio' => 0.32,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/doritos_maiz_amarillo_21g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Doritos Lemon Remix 45g',
                'descripcion' => 'Delicioso snack Doritos Lemon Remix 45g. Marca: Doritos.',
                'marca' => 'Doritos',
                'categoria' => 'Tortillas de Maiz, Limon',
                'precio' => 0.45,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/doritos_lemon_remix_45g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Doritos Dinamita 45g',
                'descripcion' => 'Delicioso snack Doritos Dinamita 45g. Marca: Dinamita.',
                'marca' => 'Dinamita',
                'categoria' => 'Tortillas de Maiz, Flammin Hot, Picantes',
                'precio' => 0.45,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/doritos_dinamita_45g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Doritos Flamin\' Hot 45g',
                'descripcion' => 'Delicioso snack Doritos Flamin\' Hot 45g. Marca: Doritos.',
                'marca' => 'Doritos',
                'categoria' => 'Tortillas de Maiz, Flammin Hot, Picantes',
                'precio' => 0.5,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/doritos_flamin_hot_45g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Doritos Flamin\' Hot 145g',
                'descripcion' => 'Delicioso snack Doritos Flamin\' Hot 145g. Marca: Doritos.',
                'marca' => 'Doritos',
                'categoria' => 'Tortillas de Maiz, Flammin Hot, Picantes',
                'precio' => 1.96,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/doritos_flamin_hot_145g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Tostitos Originales Maíz 300g',
                'descripcion' => 'Delicioso snack Tostitos Originales Maíz 300g. Marca: Tostitos.',
                'marca' => 'Tostitos',
                'categoria' => 'Tortillas de Maiz, Naturales',
                'precio' => 2.5,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/tostitos_originales_maiz_300g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'K-Chitos Naturales 30g',
                'descripcion' => 'Delicioso snack K-Chitos Naturales 30g. Marca: K-Chitos.',
                'marca' => 'K-Chitos',
                'categoria' => 'Naturales',
                'precio' => 0.6,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/k_chitos_naturales_30g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'K-Chitos Picante 30g',
                'descripcion' => 'Delicioso snack K-Chitos Picante 30g. Marca: K-Chitos.',
                'marca' => 'K-Chitos',
                'categoria' => 'Picantes',
                'precio' => 0.6,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/k_chitos_picante_30g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'K-Chitos Queso 145g',
                'descripcion' => 'Delicioso snack K-Chitos Queso 145g. Marca: K-Chitos.',
                'marca' => 'K-Chitos',
                'categoria' => 'Queso',
                'precio' => 1.8,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/k_chitos_queso_145g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Papas Lays Clásicas 20g',
                'descripcion' => 'Delicioso snack Papas Lays Clásicas 20g. Marca: Lays.',
                'marca' => 'Lays',
                'categoria' => 'Papas, Naturales',
                'precio' => 0.35,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/papas_lays_clasicas_20g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Papas Lays Clásicas 40g',
                'descripcion' => 'Delicioso snack Papas Lays Clásicas 40g. Marca: Lays.',
                'marca' => 'Lays',
                'categoria' => 'Papas, Naturales',
                'precio' => 0.65,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/papas_lays_clasicas_40g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Papas Lays Clásicas 150g',
                'descripcion' => 'Delicioso snack Papas Lays Clásicas 150g. Marca: Lays.',
                'marca' => 'Lays',
                'categoria' => 'Papas, Naturales',
                'precio' => 2.1,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/papas_lays_clasicas_150g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Papas Lays Clásicas 400g',
                'descripcion' => 'Delicioso snack Papas Lays Clásicas 400g. Marca: Lays.',
                'marca' => 'Lays',
                'categoria' => 'Papas, Naturales',
                'precio' => 4.5,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/papas_lays_clasicas_400g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Papas Lays Limón 40g',
                'descripcion' => 'Delicioso snack Papas Lays Limón 40g. Marca: Lays.',
                'marca' => 'Lays',
                'categoria' => 'Papas, Limon',
                'precio' => 0.65,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/papas_lays_limon_40g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Papas Lays Limón 150g',
                'descripcion' => 'Delicioso snack Papas Lays Limón 150g. Marca: Lays.',
                'marca' => 'Lays',
                'categoria' => 'Papas, Limon',
                'precio' => 2.1,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/papas_lays_limon_150g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Ruffles Natural 18g',
                'descripcion' => 'Delicioso snack Ruffles Natural 18g. Marca: Ruffles.',
                'marca' => 'Ruffles',
                'categoria' => 'Papas, Naturales',
                'precio' => 0.23,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/ruffles_natural_18g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Ruffles Natural 20g',
                'descripcion' => 'Delicioso snack Ruffles Natural 20g. Marca: Ruffles.',
                'marca' => 'Ruffles',
                'categoria' => 'Papas, Naturales',
                'precio' => 0.35,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/ruffles_natural_20g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Ruffles Papa Picante 40g',
                'descripcion' => 'Delicioso snack Ruffles Papa Picante 40g. Marca: Ruffles.',
                'marca' => 'Ruffles',
                'categoria' => 'Papas, Picantes',
                'precio' => 0.55,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/ruffles_papa_picante_40g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Ruffles Crema y Cebolla 38g',
                'descripcion' => 'Delicioso snack Ruffles Crema y Cebolla 38g. Marca: Ruffles.',
                'marca' => 'Ruffles',
                'categoria' => 'Papas',
                'precio' => 0.9,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/ruffles_crema_y_cebolla_38g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Ruffles Crema y Cebolla 150g',
                'descripcion' => 'Delicioso snack Ruffles Crema y Cebolla 150g. Marca: Ruffles.',
                'marca' => 'Ruffles',
                'categoria' => 'Papas',
                'precio' => 2.15,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/ruffles_crema_y_cebolla_150g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Ruffles Crema y Cebolla 400g',
                'descripcion' => 'Delicioso snack Ruffles Crema y Cebolla 400g. Marca: Ruffles.',
                'marca' => 'Ruffles',
                'categoria' => 'Papas',
                'precio' => 4.5,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/ruffles_crema_y_cebolla_400g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Ruffles Flamin\' Hot 40g',
                'descripcion' => 'Delicioso snack Ruffles Flamin\' Hot 40g. Marca: Ruffles.',
                'marca' => 'Ruffles',
                'categoria' => 'Papas, Flammin Hot, Picantes',
                'precio' => 0.6,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/ruffles_flamin_hot_40g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Platanitos Frito Lay 29g',
                'descripcion' => 'Delicioso snack Platanitos Frito Lay 29g. Marca: Platanitos.',
                'marca' => 'Platanitos',
                'categoria' => 'Naturales',
                'precio' => 0.5,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/platanitos_frito_lay_29g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Platanitos Frito Lay 40g',
                'descripcion' => 'Delicioso snack Platanitos Frito Lay 40g. Marca: Platanitos.',
                'marca' => 'Platanitos',
                'categoria' => 'Naturales',
                'precio' => 1.3,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/platanitos_frito_lay_40g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Platanitos Frito Lay 150g',
                'descripcion' => 'Delicioso snack Platanitos Frito Lay 150g. Marca: Platanitos.',
                'marca' => 'Platanitos',
                'categoria' => 'Naturales',
                'precio' => 2.2,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/platanitos_frito_lay_150g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Chicharrón Natural By Jacks 17g',
                'descripcion' => 'Delicioso snack Chicharrón Natural By Jacks 17g. Marca: Chicharron.',
                'marca' => 'Chicharron',
                'categoria' => 'Naturales',
                'precio' => 0.55,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/chicharron_natural_by_jacks_17g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Chicharrón Picante By Jacks 17g',
                'descripcion' => 'Delicioso snack Chicharrón Picante By Jacks 17g. Marca: Chicharron.',
                'marca' => 'Chicharron',
                'categoria' => 'Picantes',
                'precio' => 0.55,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/chicharron_picante_by_jacks_17g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cheetos Queso 21g',
                'descripcion' => 'Delicioso snack Cheetos Queso 21g. Marca: Cheetos.',
                'marca' => 'Cheetos',
                'categoria' => 'Queso',
                'precio' => 0.23,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/cheetos_queso_21g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cheetos Mega Queso 44g',
                'descripcion' => 'Delicioso snack Cheetos Mega Queso 44g. Marca: Cheetos.',
                'marca' => 'Cheetos',
                'categoria' => 'Queso',
                'precio' => 0.8,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/cheetos_mega_queso_44g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cheetos Mega Queso 145g',
                'descripcion' => 'Delicioso snack Cheetos Mega Queso 145g. Marca: Cheetos.',
                'marca' => 'Cheetos',
                'categoria' => 'Queso',
                'precio' => 1.9,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/cheetos_mega_queso_145g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cheetos Flamin\' Hot 44g',
                'descripcion' => 'Delicioso snack Cheetos Flamin\' Hot 44g. Marca: Cheetos.',
                'marca' => 'Cheetos',
                'categoria' => 'Queso, Flammin Hot, Picantes',
                'precio' => 0.85,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/cheetos_flamin_hot_44g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'De Todito Snack Surtido Sabor Natural 98g',
                'descripcion' => 'Delicioso snack De Todito Snack Surtido Sabor Natural 98g. Marca: De Todito.',
                'marca' => 'De Todito',
                'categoria' => 'Naturales, Papas, Tortillas de Maiz',
                'precio' => 1.25,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/de_todito_snack_surtido_sabor_natural_98g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'De Todito Snack Mix Sabor Picante 186g',
                'descripcion' => 'Delicioso snack De Todito Snack Mix Sabor Picante 186g. Marca: De Todito.',
                'marca' => 'De Todito',
                'categoria' => 'Picantes, Papas, Tortillas de Maiz',
                'precio' => 2.25,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/de_todito_snack_mix_sabor_picante_186g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'De Todito Combo Fiesta Mix 810g',
                'descripcion' => 'Delicioso snack De Todito Combo Fiesta Mix 810g. Marca: De Todito.',
                'marca' => 'De Todito',
                'categoria' => 'Naturales, Queso, Papas, Tortillas de Maiz',
                'precio' => 8.5,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/de_todito_combo_fiesta_mix_810g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Papas Artesanas Natural 40g',
                'descripcion' => 'Delicioso snack Papas Artesanas Natural 40g. Marca: Artesanas.',
                'marca' => 'Artesanas',
                'categoria' => 'Papas, Naturales',
                'precio' => 3.77,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/papas_artesanas_natural_40g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Papas Artesanas Natural 130g',
                'descripcion' => 'Delicioso snack Papas Artesanas Natural 130g. Marca: Artesanas.',
                'marca' => 'Artesanas',
                'categoria' => 'Papas, Naturales',
                'precio' => 4.8,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/papas_artesanas_natural_130g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'NatuChips Plátano Maduro 135g',
                'descripcion' => 'Delicioso snack NatuChips Plátano Maduro 135g. Marca: NatuChips.',
                'marca' => 'NatuChips',
                'categoria' => 'Naturales',
                'precio' => 2.0,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/natuchips_platano_maduro_135g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'NatuChips Plátano Verde 135g',
                'descripcion' => 'Delicioso snack NatuChips Plátano Verde 135g. Marca: NatuChips.',
                'marca' => 'NatuChips',
                'categoria' => 'Naturales',
                'precio' => 2.0,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/natuchips_platano_verde_135g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cheese Tris 52g',
                'descripcion' => 'Delicioso snack Cheese Tris 52g. Marca: Cheese Tris.',
                'marca' => 'Cheese Tris',
                'categoria' => 'Queso',
                'precio' => 0.47,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/cheese_tris_52g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cheese Tris Pequeño 42g',
                'descripcion' => 'Delicioso snack Cheese Tris Pequeño 42g. Marca: Cheese Tris.',
                'marca' => 'Cheese Tris',
                'categoria' => 'Queso',
                'precio' => 0.8,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/cheese_tris_pequeno_42g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cheese Tris Familiar 150g',
                'descripcion' => 'Delicioso snack Cheese Tris Familiar 150g. Marca: Cheese Tris.',
                'marca' => 'Cheese Tris',
                'categoria' => 'Queso',
                'precio' => 2.1,
                'cantidad_fisica' => 100,
                'en_pedidos' => 0,
                'imagen_gcs_path' => 'https://storage.googleapis.com/fritolay-images-project-3e1faa58-1e7d-4e8d-933/catalogo_web/cheese_tris_familiar_150g.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('productos')->insert($productos);
    }
}
