name: Frontend Build & Deploy

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag de versión a construir y desplegar (Ej: v1.4.15 o v1.4.15-SNAPSHOT)'
        required: true
        default: 'v1.0.0-SNAPSHOT'

jobs:
  build-and-deploy:
    name: Build & Deploy Frontend App
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP via WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Build and Push Frontend Docker Image
        run: |
          docker build \
            --build-arg VITE_APP_VERSION=${{ github.event.inputs.tag_name }} \
            --build-arg APP_VERSION=${{ github.event.inputs.tag_name }} \
            -f infra/Dockerfile.frontend \
            -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fritolay/frontend:${{ github.event.inputs.tag_name }} \
            -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fritolay/frontend:latest \
            ./frontend
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fritolay/frontend:${{ github.event.inputs.tag_name }}
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fritolay/frontend:latest

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy frontend-service \
            --image=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fritolay/frontend:${{ github.event.inputs.tag_name }} \
            --region=${{ secrets.GCP_REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars=APP_VERSION=${{ github.event.inputs.tag_name }},VITE_APP_VERSION=${{ github.event.inputs.tag_name }}
